version: "2.0"
services:
  louis:
    image: "python:3.9"
    command: bash -c "pip3 install fastapi uvicorn && uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    volumes:
      - ".:/app"
