version: "2.0"
services:
  louis:
    image: "python:3.9"
    command: bash -c "pip3 install fastapi uvicorn pymongo && uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    volumes:
      - ".:/app"
  db:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "latune"
    volumes:
       - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
    #   - ./mongo-volume:/data/db
    # expose:
    #   - 27017
    ports:
      - 27017:27017
    restart: always
